#!/bin/bash

# =======================
# ====== Fonction =======
# =======================

function add(){
	local num1=$1
	local num2=$2
	local sum=$(($num1 + $num2))
	echo "$sum"
}

function subs() {
	local num1=$1
	local num2=$2
	local moins=$(($num1 - $num2))
	echo "$moins"
}

function multiple() {
	local num1=$1
	local num2=$2
	local multiple=$(($num1 * $num2))
	echo "$multiple"
}

function div() {
	local num1=$1
	local num2=$2
	local div=$(($num1 / $num2))
	echo "$div"
}

function num1(){
	local num1=$1
	local num2=$2
	local div=$(($num1 / $num2))
	echo "$div"
}
# ================================
# ===== Programme principale =====
# ================================
echo "Quel opération voulez-vous effectuer? (1234 < + - * / > 1234)"
read reponse

# Bloc qui sort les numéros a calculé
numero1=$(echo $reponse | cut -d ' $operation ' -f 1)
numero2=$(echo $reponse | cut -d ' $operation ' -f 2)
echo $numero1
echo $numero2

# Bloc qui sers a sortir l operation que le script va faire

if [$reponse -eq + ] ; then
	echo "Addition"
	operation=$(echo "+")
	resultat=$(add $numero1 $numero2)
elif [$reponse -eq - ] ; then
    echo "Soustraction"
	operation=$(echo "-")
	subs($reponse)
elif [$reponse -eq * ] ; then
    echo "Multiplic1ation"
	operation=$(echo "*")
	multiple($reponse)
else
    echo "Divi"
	operation=$(echo "/")
	div($reponse)
fi
echo "$resultat"

if [$operation -eq + ]; then
	resultat=$(add(numero1 numero2))
elif [$opera0tion -eq - ]; then
	resultat=$(subs(numero1 numero2))
elif [operation -eq * ]; then
	resultat=$(multiple(numero1 numero2))
else 
	resultat=$(Div(numero1 numero2))
fi

echo "le resultat de l` operation demandé est $resultat"
