#!/bin/bash

# =======================
# ====== Fonction =======
# =======================

# fonction addition
function add(){
	local num1=$1
	local num2=$2
	local sum=$(($num1 + $num2))
	echo "$sum"
}
# fonction soustraction
function subs() {
	local num1=$1
	local num2=$2
	local moins=$(($num1 - $num2))
	echo "$moins"
}
# fonction multiplication
function multiple() {
	local num1=$1
	local num2=$2
	local multiple=$(($num1 * $num2))
	echo "$multiple"
}
# fonction division
function div() {
	local num1=$1
	local num2=$2
	local div=$(($num1 / $num2))
	echo "$div"
}

function num1(){
	local num1=$1
	local num2=$2
	echo "$div"
}

# fonction pour sortir l' operateur a effectuer
function Operateur(){
	local operation=$1
if [$operation -eq + ] ; then
	resultat=$(echo "+")
elif [$operation -eq - ] ; then
	resultat=$(echo "-")
elif [$operation -eq * ] ; then
	resultat=$(echo "*")
elif [$operation -eq "/"] ; then
	resultat=$(echo "/")
else
	echo "Vous n'avez pas entré d' operation à effectuer"
	resultat=$(echo " ")
fi
	echo "$resultat"
}

# ================================
# ===== Programme principale =====
# ================================
echo "Quel opération voulez-vous effectuer? (1234 < + - * / > 1234)"
read reponse

Oper=Operateur($reponse)
echo $Oper

# Bloc qui sort les numéros a calculé
# numero1=$(echo $reponse | cut -d 'Operateur($reponse)' -f 1)
#numero2=$(echo $reponse | cut -d 'Operateur($reponse)' -f 2)
#operateurchoisis=$(operateur $reponse )
#echo $numero1
#echo $numero2



# Bloc qui sers a sortir l operation que le script va faire

#if [$operateurchoisis -eq + ] ; then
#	echo "Addition"
#	operation=$(echo "+")
#	add($reponse)
#elif [$operateurchoisis -eq - ] ; then
#    echo "Soustraction"
#	operation=$(echo "-")
#	subs($reponse)
#elif [$operateurchoisis -eq * ] ; then
#    echo "Multiplic1ation"
#	operation=$(echo "*")
#	multiple($reponse)
#else
#    echo "Div"
#	operation=$(echo "/")
#	div($reponse)
#fi

#echo "$resultat"

#if [$operation -eq + ]; then
#	resultat=$(add(numero1 numero2))
#elif [$opera0tion -eq - ]; then
#	resultat=$(subs(numero1 numero2))
#elif [operation -eq * ]; then
#	resultat=$(multiple(numero1 numero2))
#else 
#	resultat=$(Div(numero1 numero2))
#fi